export const MAJORS = [
    'Accounting',
    'Biology',
    'Business',
    'Chemistry',
    'Communications',
    'Computer Science',
    'Economics',
    'Education',
    'Engineering',
    'English',
    'Finance',
    'History',
    'Information Technology',
    'Marketing',
    'Mathematics',
    'Nursing',
    'Political Science',
    'Psychology',
    'Sociology',
];
